os: Visual Studio 2015

environment:
  matrix:
    - arch: x64
      compiler: MinGW-w64

platform:
  - x64

install:
  - appveyor-retry appveyor DownloadFile http://downloads.sourceforge.net/mingw-w64/x86_64-7.1.0-release-posix-seh-rt_v5-rev0.7z
  - 7z x x86_64-7.1.0-release-posix-seh-rt_v5-rev0.7z -oc:\mingw > nul
  - set NINJA_URL="https://github.com/ninja-build/ninja/releases/download/v1.6.0/ninja-win.zip"
  - appveyor-retry appveyor DownloadFile %NINJA_URL% -FileName ninja.zip
  - 7z x ninja.zip -oC:\ninja > nul
  - set PATH=C:\ninja;C:\mingw\mingw64\bin;%PATH%
  - ninja --version
  - C:\python34-x64\pip install meson

build_script:
  - echo Building on %arch% with %compiler%
  - set PATH=%cd%;C:\python34-x64;%PATH%;
  - python meson.py --backend=ninja builddir
  - ninja -C builddir
